services:
  frontend:
    image: node:20
    working_dir: /app
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host", "--port", "${FRONTEND_PORT}"]
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    env_file: ./backend/.env
    environment:
      - NO_SQLITE=true
    command: ["node", "index.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

networks:
  app-network:
    driver: bridge
